/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_5D105E7__
#define __PLUGINEDITOR_H_5D105E7__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class LedsignVizAudioProcessorEditor  : public AudioProcessorEditor, public Timer
{
public:
    LedsignVizAudioProcessorEditor (LedsignVizAudioProcessor* ownerFilter);
    ~LedsignVizAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);

	void timerCallback();
private:
	int scale;
};


#endif  // __PLUGINEDITOR_H_5D105E7__
